#!/usr/bin/python3
"""
    101-lazy_matrix_mul.py
    Module that defines a method for multiplying 2 matrices using numpy
"""

import numpy as np


def lazy_matrix_mul(m_a, m_b):
    """
    Function that takes 2 matrices as parameter and returns
    a new matrix whose elements are the multiplication of each
    element of each matrix using numpy module
    Args:
        m_a (list): First matrix
        m_b (list): Second matrix
    Notes:
        Exceptions for wrong arguments will be generated by numpy module
    """
    return np.matmul(m_a, m_b)
